// <auto-generated />
using System;
using GeedService.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeedService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeedService.DataEntities.UserProfile", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("Bio")
                        .HasMaxLength(200);

                    b.Property<string>("FacebookId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("InstagramId");

                    b.Property<DateTime>("Joined");

                    b.Property<string>("LinkedInId");

                    b.Property<string>("TwitterId");

                    b.Property<string>("Username")
                        .HasMaxLength(12);

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("GeedService.Model.Following", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FollowedUserName")
                        .IsRequired();

                    b.Property<string>("FollowerUserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Followings");
                });

            modelBuilder.Entity("GeedService.Model.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GivenRating");

                    b.Property<string>("RatedUserName")
                        .IsRequired();

                    b.Property<string>("RaterUserName")
                        .IsRequired();

                    b.Property<DateTime>("TimeRated");

                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
